# Variables to inject into Java variables
ebayClientId: ${EBAY_CLIENT_ID}
ebayClientSecret: ${EBAY_CLIENT_SECRET}
ebayTokenUrl: ${EBAY_TOKEN_URL}

logging:
  level:
    root: warn
server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ebay-user-auth-service
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_URI}/${DATASOURCE_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
  devtools:
    livereload:
      port: ${LIVERELOAD_PORT:35730}
      enabled: true
  cloud:
    loadbalancer:
      enabled: true
      cache:
        enabled: true
